# Generated by Django 4.2.1 on 2023-07-25 11:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostmodel",
            name="blog_text",
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="authormodel",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="authormodel",
            name="social_media_links",
        ),
        migrations.AlterField(
            model_name="blogpostmodel",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="category_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="commentmodel",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contactmodel",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tagmodel",
            name="tag_name",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="OrdinaryUserModel",
        ),
        migrations.AddField(
            model_name="authormodel",
            name="occupation",
            field=models.ManyToManyField(to="blog.authoroccupationmodel"),
        ),
        migrations.AddField(
            model_name="authormodel",
            name="social_media_links",
            field=models.ManyToManyField(to="blog.socialmediamodel"),
        ),
    ]
