# Generated by Django 4.2.1 on 2023-07-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_remove_blogpostmodel_blog_text_blogpostmodel_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authormodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="contactmodel",
            name="name",
        ),
        migrations.AddField(
            model_name="authormodel",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactmodel",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
