# Generated by Django 4.2.1 on 2023-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_authormodel_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authormodel",
            name="email",
        ),
        migrations.RemoveField(
            model_name="authormodel",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="authormodel",
            name="user",
        ),
        migrations.AddField(
            model_name="authormodel",
            name="name",
            field=models.TextField(default="Annonymous User"),
        ),
    ]
