# Generated by Django 4.2.1 on 2023-07-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_authormodel_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostmodel",
            name="hashtag",
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="hashtag",
            field=models.ManyToManyField(to="blog.tagmodel"),
        ),
    ]
