# Generated by Django 4.2.1 on 2023-07-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
