# Generated by Django 4.2.1 on 2023-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_blogpostmodel_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostmodel",
            name="date_time",
            field=models.DateField(auto_now=True),
        ),
    ]
