# Generated by Django 4.2.1 on 2023-07-26 03:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_blogpostmodel_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_af",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ar",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ar_dz",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ast",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_az",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_be",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_bg",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_bn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_br",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_bs",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ca",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ckb",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_cs",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_cy",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_da",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_de",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_dsb",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_el",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_en_au",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_en_gb",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_eo",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_es",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_es_ar",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_es_co",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_es_mx",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_es_ni",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_es_ve",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_et",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_eu",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_fa",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_fi",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_fr",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_fy",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ga",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_gd",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_gl",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_he",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_hi",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_hr",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_hsb",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_hu",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_hy",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ia",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ig",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ind",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_io",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_is",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_it",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ja",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ka",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_kab",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_kk",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_km",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_kn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ko",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ky",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_lb",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_lt",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_lv",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_mk",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ml",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_mn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_mr",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ms",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_my",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_nb",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ne",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_nl",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_nn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_os",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_pa",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_pl",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_pt",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_pt_br",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ro",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ru",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sk",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sl",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sq",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sr",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sr_latn",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sv",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_sw",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ta",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_te",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_tg",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_th",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_tk",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_tr",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_tt",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_udm",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_uk",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_ur",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_uz",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_vi",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_zh_hans",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="text_zh_hant",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_af",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ar_dz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ast",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_az",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_be",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_bg",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_bn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_br",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_bs",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ca",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ckb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_cs",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_cy",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_da",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_dsb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_el",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_en_au",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_en_gb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_eo",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_es_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_es_co",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_es_mx",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_es_ni",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_es_ve",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_et",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_eu",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_fa",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_fi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_fy",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ga",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_gd",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_gl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_he",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_hi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_hr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_hsb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_hu",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_hy",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ia",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ig",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ind",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_io",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_is",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_it",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ja",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ka",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_kab",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_kk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_km",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_kn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ko",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ky",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_lb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_lt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_lv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_mk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ml",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_mn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_mr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ms",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_my",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_nb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ne",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_nl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_nn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_os",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_pa",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_pl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_pt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_pt_br",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ro",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sq",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sr_latn",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_sw",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ta",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_te",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_tg",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_th",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_tk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_tr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_tt",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_udm",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_uk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_ur",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_vi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_zh_hans",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogpostmodel",
            name="title_zh_hant",
            field=models.TextField(null=True),
        ),
    ]
