# Generated by Django 4.2.1 on 2023-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_remove_blogpostmodel_title_af_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostmodel",
            name="title",
            field=models.CharField(default="Title", max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpostmodel",
            name="title_de",
            field=models.CharField(default="Title", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blogpostmodel",
            name="title_en",
            field=models.CharField(default="Title", max_length=100, null=True),
        ),
    ]
