# Generated by Django 4.2.1 on 2023-07-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_blogpostmodel_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostmodel",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
