# Generated by Django 4.2.1 on 2023-07-26 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_blogpostmodel_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostmodel",
            name="created",
        ),
    ]
