# Generated by Django 4.2.1 on 2023-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_alter_blogpostmodel_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagevisit",
            name="url",
        ),
        migrations.AddField(
            model_name="pagevisit",
            name="device_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="viewcountmodel",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
