# Generated by Django 4.2.1 on 2023-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_remove_pagevisit_url_pagevisit_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewcountmodel",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
