# Generated by Django 4.2.1 on 2023-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_rename_authormodel_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
