# Generated by Django 4.2.1 on 2023-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_alter_blogpost_title_alter_blogpost_title_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default="Anonymous", max_length=40),
        ),
    ]
